### ISSUE TITLE
Suppress IDE0066 - 'Convert switch statement to switch expression'

### ISSUE THREAD

**Issue by SilentSin** [microsoft/Microsoft.Unity.Analyzers#34] opened 2020-02-26 22:51 UTC
#### Problem statement
Unity (2019.3.2f1) doesn't support switch expressions.

#### Proposed solution
Suppress the code style suggestion IDE0066 - 'Convert switch statement to switch expression'.

**Comment by sailro** [comment] 2020-02-27 16:54
This is probably related to how Unity setups C# language version support when generating the csproj file. This should be solved with Unity 2020 (using packages for external editor support).

**Comment by jbevain** [comment] 2020-02-28 22:26
Hi, thanks for your suggestion!

I agree with @sailro here, if anything that's a bug in the project generation. Right now we have a fix for Unity 2020.1, but we don't have a fix for previous versions. I'm going to close this because the root of the issue is outside of the scope of the analyzers, but we should definitely investigate fixing this issue in VSTU.

**Closed by jbevain** 2020-02-28 22:26 UTC
