### ISSUE TITLE
Static Fields and Static Event Handlers analyzers for disabling domain reload on entering playmode

### ISSUE THREAD

**Issue by crocodileindie** [microsoft/Microsoft.Unity.Analyzers#225] opened 2022-06-19 15:00 UTC
#### Problem statement
This feature https://docs.unity3d.com/Manual/ConfigurableEnterPlayMode.html can save users lots of time but comes with hard to identify restrictions especially if you use packages or asset store code
https://docs.unity3d.com/Manual/DomainReloading.html
#### Proposed solution
Static Fields and Static Event Handlers analyzers for disabling domain reload on entering playmode

**Comment by sailro** [comment] 2022-06-21 07:26
cc @jbevain

**Comment by SilentSin** [comment] 2022-07-09 04:26
Could an analyser use reflection to check the setting if the UnityEditor.dll is loaded to avoid needing a direct dependency?

**Comment by sailro** [comment] 2022-07-22 13:13
I think we need to improve the project generation process to include a define telling us the proper context (is domain reload enabled ?). And we need also to force a re-gen when enabling/disabling this setting in Unity. We are going to discuss that in our next meeting with Unity folks.

**Comment by sailro** [comment] 2024-06-03 06:24
Closing as Unity has plans to automate this part with dedicated tooling/analyzers.

**Closed by sailro** 2024-06-03 06:24 UTC
Labels: investigating

**Comment by bdovaz** [comment] 2024-06-03 07:56
> Closing as Unity has plans to automate this part with dedicated tooling/analyzers.

The problem is that if it has to do with the migration to CoreCLR, they want to do everything all at once so we will not see all this until at least 2025/2026...

I would be nice to have a temporary solution in the meantime....

**Comment by sailro** [comment] 2024-06-03 08:12
@bdovaz, yes I fully agree it would be nice to have that as well for the Mono runtime. But if they come with a solution based on analyzers to detect static patterns, we will probably be able to reuse that. I plan to discuss this with them, on our next technical meeting.

**Comment by NuclearCookie** [comment] 2024-10-21 13:29
Hi, did anything come up during the technical meeting?
